version: "3.4"
services:
  pgcheck:
    build:
      context: .
      dockerfile: Dockerfile
      target: appbuild
    image: checkpg_appbuild
    container_name: checkpg_service
    depends_on:
      - pgsql
    environment:
      - POSTGRES_ADDR
      - POSTGRES_PASSWORD
      - POSTGRES_USER
  pgsql:
    container_name: checkpg_postgres
    image: postgres:13.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1pgpassword1
  run_test:
    depends_on:
      - pgcheck
    image: curlimages/curl:7.77.0
    container_name: checkpg_integration_test
    command: [ "/bin/sh", "-c", '[ "$$(curl -s http://pgcheck:7654)" = "$$EXPECT_RESPONSE" ]' ]
    environment:
      - EXPECT_RESPONSE
