name: integration tests
on: [push]
jobs:
  run_integration_tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        run: ./run_tests.sh
