name: integration tests
on: [push]
jobs:
  run_integration_tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        run: ./run_tests.sh
  build_docker_image:
    needs:
     - run_integration_tests
    runs-on: ubuntu-latest
    steps:
      #-
      #  name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v1
      -
        name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: mxpatlas/checkpg_minimal:latest
          push: false
